baseURL = 'https://cheuk-blog.github.io/'
languageCode = 'en-us'
title = 'Cheuk-Blog'

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[params]
  contentDir = "posts"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
